version: 1.0
provider:
  name: openfaas
functions:
  phpscraper:
    lang: php7
    environment:
      content_type: application/json
    secrets:
      - phpscraper-api-token
    handler: ./phpscraper
    image: spekulatius/faasd-phpscraper:latest
